src/app/Models/Links/CheckViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Linx.Domain;
using static Linx.Functions.Functions;

namespace Linx.Models.Links
{
    public class CheckViewModel
    {
        [Required]
        public Guid ID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Url { get; set; }

        public string Abstract { get; set; }

        public string Tags { get; set; }

        public IEnumerable<Tag> AllTags { get; set; }

        public string TagDataJson =>
            AllTags?.AsTagJson(t => t.Label);

        public static UpdateViewModel From(Link link, IEnumerable<Tag> allTags) =>
            new() {
                ID = link.ID,
                Title = link.Title,
                Url = link.Url,
                Abstract = link.Abstract,
                Tags = string.Join("|", link.Tags.Select(t => t.Label)),
                AllTags = allTags
            };

        public static Link ToLink(UpdateViewModel model) =>
            new(
                model.ID,
                model.Title,
                model.Url,
                model.Abstract,
                (model.Tags ?? string.Empty)
                    .Split('|', StringSplitOptions.RemoveEmptyEntries)
                    .Select(t => new Tag(t))
            );
    }
}

src/app/Models/Links/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Linx.Domain;
using static Linx.Functions.Functions;

namespace Linx.Models.Links
{
    public class CreateViewModel
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public string Url { get; set; }

        public string Abstract { get; set; }

        public string Tags { get; set; }

        public IEnumerable<Tag> AllTags { get; set; }

        public string TagDataJson =>
            AllTags?.AsTagJson(t => t.Label);

        public static CreateViewModel From(IEnumerable<Tag> allTags) =>
            new() {
                AllTags = allTags
            };

        public static Link ToLink(CreateViewModel model) =>
            new(
                Guid.NewGuid(),
                model.Title,
                model.Url,
                model.Abstract,
                (model.Tags ?? string.Empty)
                    .Split('|', StringSplitOptions.RemoveEmptyEntries)
                    .Select(t => new Tag(t))
            );
    }
}

src/app/Models/Links/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Linx.Data;
using Linx.Models.Shared;

namespace Linx.Models.Links
{
    public class IndexViewModel
    {
        public PaginationDetails Pagination { get; set; }

        public IEnumerable<ListViewLinkViewModel> Links { get; set; }

        public string PageLinkWith(
            int? page = null,
            int? pageSize = null,
            SortColumn? sort = null,
            SortDirection? sortDirection = null,
            string query = null)
        {
            var parameters = new Dictionary<string, object> {
                { "page", page ?? Pagination.Page },
                { "pageSize", pageSize ?? Pagination.PageSize },
                { "sort", sort ?? Pagination.Sort },
                { "sortDirection", sortDirection ?? Pagination.SortDirection },
                { "query", Uri.EscapeDataString(query ?? Pagination.Query) }
            };

            var queryString = string.Join("&", parameters.Select(p => $"{p.Key}={p.Value}"));

            return "?" + queryString;
        }

        public string PageSizeLinkClassesFor(int pageSize) =>
            pageSize == Pagination.PageSize
                ? "btn btn-primary active"
                : "btn btn-outline-primary";

        public string SortLinkClassesFor(SortColumn sort, SortDirection sortDirection) =>
            sort == Pagination.Sort && sortDirection == Pagination.SortDirection
                ? "btn btn-primary active"
                : "btn btn-outline-primary";
    }
}

src/app/Models/Links/UpdateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Linx.Domain;
using static Linx.Functions.Functions;

namespace Linx.Models.Links
{
    public class UpdateViewModel
    {
        [Required]
        public Guid ID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Url { get; set; }

        public string Abstract { get; set; }

        public string Tags { get; set; }

        public IEnumerable<Tag> AllTags { get; set; }

        public string TagDataJson =>
            AllTags?.AsTagJson(t => t.Label);

        public static UpdateViewModel From(Link link, IEnumerable<Tag> allTags) =>
            new() {
                ID = link.ID,
                Title = link.Title,
                Url = link.Url,
                Abstract = link.Abstract,
                Tags = string.Join("|", link.Tags.Select(t => t.Label)),
                AllTags = allTags
            };

        public static Link ToLink(UpdateViewModel model) =>
            new(
                model.ID,
                model.Title,
                model.Url,
                model.Abstract,
                (model.Tags ?? string.Empty)
                    .Split('|', StringSplitOptions.RemoveEmptyEntries)
                    .Select(t => new Tag(t))
            );
    }
}

src/app/Models/ListViewLinkViewModel.cs
using Linx.Domain;

namespace Linx.Models
{
    public class ListViewLinkViewModel
    {
        public PaginationDetails Pagination { get; set; }

        public ListViewLink Link { get; set; }
    }
}

src/app/Models/Shared/ListViewLinkViewModel.cs
using Linx.Domain;

namespace Linx.Models.Shared
{
    public class ListViewLinkViewModel
    {
        public PaginationDetails Pagination { get; set; }

        public ListViewLink Link { get; set; }
    }
}

src/app/Models/Shared/PaginationDetails.cs
using System.Collections.Generic;
using System.Linq;
using Linx.Data;
using Linx.Domain;

namespace Linx.Models.Shared
{
    public class PaginationDetails
    {
        public int Total { get; set; }

        public int PageSize { get; set; }

        public int Pages { get; set; }

        public int Page { get; set; }

        public int DirectPageLinksEitherSideOfCurrent { get; set; } = 5;

        public IEnumerable<int> DirectPageLinksBefore
        {
            get
            {
                var start = Page - DirectPageLinksEitherSideOfCurrent;

                return start < 1
                    ? Enumerable.Range(1, DirectPageLinksEitherSideOfCurrent + start - 1)
                    : Enumerable.Range(start, DirectPageLinksEitherSideOfCurrent);
            }
        }

        public IEnumerable<int> DirectPageLinksAfter
        {
            get
            {
                var end = Page + DirectPageLinksEitherSideOfCurrent;

                return end > Pages
                    ? Enumerable.Range(Page + 1, Pages - Page)
                    : Enumerable.Range(Page + 1, DirectPageLinksEitherSideOfCurrent);
            }
        }

        public SortColumn Sort { get; set; }

        public SortDirection SortDirection { get; set; }

        public IEnumerable<Tag> Tags { get; set; }

        public string Query =>
            string.Join(" ", Tags.Select(t => $"[{t.Label}]"));
    }
}

src/app/Controllers/LinksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Linx.Data;
using Linx.Models.Links;
using Linx.Models.Shared;
using Linx.Services;
using Linx.Support;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using static Linx.Functions.Functions;

namespace Linx.Controllers
{
    public class LinksController : ControllerBase
    {
        private readonly ISearchService _searchService;

        public LinksController(
            IOptionsMonitor<Settings> optionsMonitor,
            IRepository repository,
            ISearchService searchService)
            : base(
                optionsMonitor,
                repository) =>
            _searchService = searchService;

        [HttpGet]
        public async Task<IActionResult> Index(
            int page = 1,
            int pageSize = 10,
            SortColumn sort = SortColumn.Created,
            SortDirection sortDirection = SortDirection.Descending,
            string query = null)
        {
            var (parsed, terms, tags) = ParseSearchQuery(query);

            var (total, pageCount, links) = await Repository.ReadLinksAsync(UserID, page, pageSize, sort, sortDirection, tags);

            var pagination = new PaginationDetails {
                Total = total,
                Pages = pageCount,
                PageSize = pageSize,
                Page = page,
                Sort = sort,
                SortDirection = sortDirection,
                Tags = tags
            };

            var model = new IndexViewModel {
                Pagination = pagination,
                Links = links.Select(l => new ListViewLinkViewModel { Link = l, Pagination = pagination })
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var allTags = await Repository.ReadAllTagsAsync(UserID);

            var model = CreateViewModel.From(allTags);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.AllTags = await Repository.ReadAllTagsAsync(UserID);

                return View(model);
            }

            var create = CreateViewModel.ToLink(model);

            var link = await Repository.CreateLinkAsync(UserID, create);

            _searchService.AddLink(UserID, link);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var link = await Repository.ReadLinkAsync(UserID, id);

            if (link == null)
            {
                return NotFound();
            }

            var allTags = await Repository.ReadAllTagsAsync(UserID);

            return link != null
                ? View(UpdateViewModel.From(link, allTags))
                : NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.AllTags = await Repository.ReadAllTagsAsync(UserID);

                return View(model);
            }

            var update = UpdateViewModel.ToLink(model);

            var link = await Repository.UpdateLinkAsync(UserID, update);

            _searchService.UpdateLink(UserID, link);

            return RedirectToAction(nameof(Update), new { id = link.ID });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            await Repository.DeleteLinkAsync(UserID, id);

            _searchService.RemoveLink(UserID, id);

            return RedirectToAction(nameof(Index));
        }
    }
}

src/app/Controllers/SearchController.cs
using System.Threading.Tasks;
using Linx.Data;
using Linx.Models.Search;
using Linx.Services;
using Linx.Support;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Linx.Controllers
{
    public class SearchController : ControllerBase
    {
        private readonly ISearchService _searchService;

        public SearchController(
            IOptionsMonitor<Settings> optionsMonitor,
            IRepository repository,
            ISearchService searchService)
            : base(
                optionsMonitor,
                repository) =>
            _searchService = searchService;

        public IActionResult Index(IndexViewModel model)
        {
            model.Results = _searchService.Search(UserID, model.Query);

            return View(model);
        }

        // TODO: Remove and integrate into UI
        public async Task<IActionResult> RecreateIndex()
        {
            var (_, _, links) = await Repository.ReadLinksFullAsync(UserID, 1, 9999, SortColumn.Created, SortDirection.Descending);

            _searchService.DeleteAndRebuildIndex(UserID, links);

            return Ok("OK");
        }
    }
}

src/app/Controllers/TagsController.cs
using System.Threading.Tasks;
using Linx.Data;
using Linx.Models.Tags;
using Linx.Services;
using Linx.Support;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Linx.Controllers
{
    public class TagsController : ControllerBase
    {
        private readonly ISearchService _searchService;

        public TagsController(
            IOptionsMonitor<Settings> optionsMonitor,
            IRepository repository,
            ISearchService searchService)
            : base(
                optionsMonitor,
                repository) =>
            _searchService = searchService;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = new IndexViewModel {
                Tags = await Repository.ReadAllTagsAsync(UserID)
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Merge()
        {
            var model = new MergeViewModel {
                Tags = await Repository.ReadAllTagsAsync(UserID)
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Merge(MergeViewModel model)
        {
            await Repository.MergeTagsAsync(UserID, model.TagID, model.TagIDsToMerge);

            var (_, _, links) = await Repository.ReadLinksFullAsync(UserID, 1, 9999, SortColumn.Created, SortDirection.Descending);

            _searchService.DeleteAndRebuildIndex(UserID, links);

            return RedirectToAction(nameof(Merge));
        }
    }
}

src/app/Controllers/UsersController.cs
using System.Threading.Tasks;
using Linx.Models.Users;
using Linx.Services;
using Linx.Support;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using static Linx.Domain.Constants;

namespace Linx.Controllers
{
    public class UsersController : Controller
    {
        private readonly Settings _cfg;
        private readonly IDateTimeService _dateTimeService;
        private readonly IUserService _userService;

        public UsersController(
            IOptionsMonitor<Settings> optionsMonitor,
            IDateTimeService dateTimeService,
            IUserService userService)
        {
            _cfg = optionsMonitor.CurrentValue;
            _dateTimeService = dateTimeService;
            _userService = userService;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            var model = new LoginViewModel {
                ReturnUrl = returnUrl
            };

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var (valid, user) = await _userService.ValidateLogin(model.Email, model.Password);

            if (!valid)
            {
                return View(model);
            }

            var principal = _userService.GetClaimsPrincipal(user);

            var authenticationProperties = new AuthenticationProperties {
                IsPersistent = true,
                ExpiresUtc = _dateTimeService.Now.AddDays(_cfg.PersistentSessionLengthInDays)
            };

            await HttpContext.SignInAsync(principal, authenticationProperties);

            var returnUrl = !string.IsNullOrWhiteSpace(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl)
                ? model.ReturnUrl
                : SiteRootUrl;

            return Redirect(returnUrl);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return Redirect(SiteRootUrl);
        }
    }
}

src/app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex">
    <title>Linx</title>
    <link rel="preload" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/fonts/bootstrap-icons.woff2?4601c71fb26c9277391ec80789bfde9c" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/fonts/bootstrap-icons.woff?4601c71fb26c9277391ec80789bfde9c" as="font" type="font/woff" crossorigin>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet" integrity="sha256-MsxKR7Nw4ngHKmRAJJhy5oHvodmSYAQgwDqWMdqIXXA=" crossorigin="anonymous">
    <link href="~/css/main.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Links" asp-action="Index">LINX</a>
            @if (User.Identity.IsAuthenticated)
            {
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Links" asp-action="Create">New Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="tags-dropdown" data-bs-toggle="dropdown" aria-expanded="false">Tags</a>
                            <ul class="dropdown-menu" aria-labelledby="tags-dropdown">
                                <li><a class="dropdown-item" asp-controller="Tags" asp-action="Index">All Tags</a></li>
                                <li class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Tags" asp-action="Merge">Manage Tags</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <span class="nav-link">@(User?.FindFirst(ClaimTypes.Email)?.Value)</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Users" asp-action="Logout">Log Out</a>
                        </li>
                    </ul>
                    <form class="d-flex" asp-controller="Search" asp-action="Index" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" value="@ViewBag.SearchQuery">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            }
        </div>
    </nav>
    <main class="container">
        @RenderBody()
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    @await RenderSectionAsync("globals", required: false)
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

src/app/Views/Shared/_Link.cshtml
@model Link

<div class="link">
    <h2><a href="@Model.Url">@Model.Title</a> <a class="link-edit" asp-controller="Links" asp-action="Update" asp-route-id="@Model.ID">Edit</a></h2>

    <p class="link-abstract">@Model.Abstract</p>

    <tag-links tags="Model.Tags" />
</div>

src/app/Views/Shared/_ListViewLink.cshtml
@model Linx.Models.Shared.ListViewLinkViewModel

<div class="link">
    <h2><a href="@Model.Link.Url">@Model.Link.Title</a> <a class="link-edit" asp-controller="Links" asp-action="Update" asp-route-id="@Model.Link.ID">Edit</a></h2>

    <p class="link-abstract">@Model.Link.Abstract</p>

    <tag-badges tags="Model.Link.Tags" pagination="Model.Pagination" container-classes="tag-links" badge-classes="badge bg-primary" copy-button="true" />
</div>